Using Bootstrap to create a clone of the NewsWeek Landing Page
t-yanick/using-bootstrap pull request #2
Opened 2020-08-14 18:28 UTC by t-yanick

This is a collaborative microverse project, but unfortunately Student Sucess asked me to work on it solo because I waited for a coding partner re-pair for too long.

- This project was built using bootstrap and a little bit of CSS for empahis or to overwrite some bootstrap properties

2020-08-15 00:20 UTC, lmaldonadoch requested changes
# [STATUS] Changes Required 🥇 🏃‍♂️

## Great job, @t-yanick!!! 🏆

This was me reviewing your project:

<img src="https://media.giphy.com/media/MuTenSRsJ7TQQ/giphy.gif" />

## It is **A-MA-ZING**

You used Bootstrap for pretty much everything you kept the CSS to a minimum :clap: :clap: :clap:

The use of semantic HTML was almost flawless; your attention to detail was breathtaking. You have a very beautiful project here.

There are some quick changes that we need to implement before moving on, and one that might not be s quick but I tried to give you a hint, so here they are:


- [x] [REQUIRED] On medium size, the weekly issue should be as tall as the height of the row. Also, take a look at how the section name wraps when getting close to sm size. Please fix both.
![image](https://user-images.githubusercontent.com/59229758/90300965-9cf9cf80-de62-11ea-89bb-6eaf712036c1.png)

- [x] [REQUIRED] On sm, Top stories should come first, then Featured Stories, then Debate, Opinion, More Stories, and My Turn before the sponsored section. Hint :bulb: Do the same that you did with your Navbar (d-none).

- [x] [OPTIONAL] Keep an eye on these small details, your website is so good that you should work towards making it perfect!
![image](https://user-images.githubusercontent.com/59229758/90300978-b13dcc80-de62-11ea-968a-d15fa6c0372d.png)

- [x] [OPTIONAL] Same here, Keep an eye on the alignment and the margins. The devil is in the details! :smiling_imp:
![image](https://user-images.githubusercontent.com/59229758/90300995-c0247f00-de62-11ea-9268-1e00c01cf729.png)

- [x] [OPTIONAL] Add a Getting Started section to your README, here you can include how to clone your repo and how to launch it on a local machine. In this section, you should be instructions for non-tech people to work with your project.

- [ ] [OPTIONAL] Make the font of the titles smaller and bold, to match the original website.
![image](https://user-images.githubusercontent.com/59229758/90301023-ec400000-de62-11ea-833e-2a60e7a71edc.png)

- [x] [OPTIONAL] Make the date bold and a link, as in the original website
![image](https://user-images.githubusercontent.com/59229758/90301039-0c6fbf00-de63-11ea-8e3f-fe7b297a1764.png)

- [x] [OPTIONAL] Use a `<nav>` tag for your Navbar, remember that semantic HTML is important.

## You are almost there!!! 

Please implement the required changes, and consider implementing the optional ones. Please reach out if you have any question.

It was a pleasure reviewing your code,

Happy coding! 💻

Slack: Luis Angel Maldoando
[LinkedIn](https://www.linkedin.com/in/lmaldonadoch/)

2020-08-16 16:37 UTC, t-yanick commented
- Thanks for your review @lmaldonadoch . Thanks for responding to my messages on slack. You were the coding partner I didn't have for this project. 

- Requested changes fixed including the optional ones.

2020-08-16 17:29 UTC, lmaldonadoch requested changes
# [STATUS] Changes Required 🥇 🏃‍♂️

## Amazing job, @t-yanick!!! 👍 👏 

## You were

<img src="https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif" />

### Your project aesthetically is ready! There is just a small tiny issue with the ordering. Here is your project vs the original one:

| Your Project  | Newsweek Website  |
|--:|--:|
|![screencapture-raw-githack-t-yanick-2](https://user-images.githubusercontent.com/59229758/90339935-08a28080-dfba-11ea-99ef-18c891a214a5.jpg)|![screencapture-newsweek-Tazoh](https://user-images.githubusercontent.com/59229758/90339906-e1e44a00-dfb9-11ea-8ed3-3f8fe093e2f5.jpg)|

- [ ] [REQUIRED] The sections must be in the same order as the original website. Can you notice how the Debate/Opinion section is pushed down by the Sponsored Section? Then, the next section should be More Stories. In your project, the next section that appears is My Turn, and at the end is where the Sponsored Section should appear. Hint :bulb: In your code, there is no clear distinction on where a section ends and where it begins. If you could wrap each section in the appropriate `<section>` tag, then you would be able to order them using the `order` class.

## You are almost there!!! 

Your project is one of the best Bootstrap projects I have seen, your implementation of the classes is incredible and the cleanness of your code is also remarkable. 

<img src="https://media.giphy.com/media/a0Lgc1JvbfS4o/giphy.gif" />

It was a pleasure reviewing your code,

Happy coding! 💻

Slack: Luis Angel Maldoando
[LinkedIn](https://www.linkedin.com/in/lmaldonadoch/)

2020-08-16 17:58 UTC, t-yanick commented
Thanks for the review.

- Sent the sponsored and insight section after the opinion section.

2020-08-16 18:01 UTC, t-yanick commented
Thanks very much @lmaldonadoch  for your review and very encouraging comments

2020-08-16 18:42 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi @t-yanick ! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! As was mentioned by the previous TSE, your project looks amazing!! 🤩 🤩  Go ahead and merge this pull request and keep up the good work 😄
****
### [OPTIONAL]

- There is still a `.DS_Store` file in your images folder. It normally is a requirement to ensure that all instances of `.DS_Store` are removed but as your previous reviewer missed it I've marked it as optional. I have found this [stack overflow discussion](https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository) to be the most useful in tracking all instances of the `.DS_Store` files and removing them 

_P.S. Make sure to update the live demo link in your README file_ 😄 

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-08-16 21:59 UTC, merged